Repository cylc/cylc-uiserver, pull requests merged in 2021-09, with the labels that each got.

#241 Update schema for cylc play
  CHANGES.md
  cylc/uiserver/schema.py
Labels: bug, small

#245 setup.cfg: fix packaging
  MANIFEST.in
  setup.cfg
Labels: bug

#234 data-store sync reconciliation fixed
  cylc/uiserver/data_store_mgr.py
Labels: bug

#246 Add py.typed
  MANIFEST.in
  cylc/uiserver/py.typed
Labels: small

#248 Replace NBSP by space
  setup.cfg
Labels: small

#249 packaging: fix packaging
  MANIFEST.in
  setup.cfg
Labels: bug
