Repository cylc/cylc-uiserver, pull requests merged in 2021-11, with the labels that each got.

#270 Remove ping from the UI server
  cylc/uiserver/authorise.py
  cylc/uiserver/tests/test_authorise.py
Labels: small

#266 Fix Delta clashes & upgrade graphql-ws & graphql-tornado-ws
  cylc/uiserver/handlers.py
  cylc/uiserver/websockets/tornado.py
  setup.cfg
Labels: bug, efficiency

#272 Have authorise handle key errors when getting group names from ids
  CHANGES.md
  cylc/uiserver/app.py
  cylc/uiserver/authorise.py
  cylc/uiserver/tests/test_authorise.py
Labels: bug

#274 Reinstate/fix multi-workflow request filter
  cylc/uiserver/resolvers.py
  cylc/uiserver/workflows_mgr.py
Labels: small

#277 Fix log bug
  cylc/uiserver/authorise.py
Labels: bug

#279 actions: fix release action
  .github/workflows/1_create_release_pr.yml
Labels: infrastructure

#285 Fix long description content type setting in setup.cfg
  setup.cfg
Labels: small
