Repository cylc/cylc-uiserver, pull requests merged in 2022-03, with the labels that each got.

#326 README update of UIServer config path
  README.md
Labels: small

#336 Fix lack of upper pin for `rx` in `graphql-core<2.3.0`
  cylc/uiserver/authorise.py
  cylc/uiserver/workflows_mgr.py
  setup.cfg
Labels: small, dependencies

#338 Ignore flake8-simplify experimental 9xx rules.
  tox.ini
Labels: infrastructure
