Repository cylc/cylc-uiserver, pull requests merged in 2022-02, with the labels that each got.

#302 Autodoc traits Followup
  cylc/uiserver/app.py
Labels: small

#284 actions: test build on project metadata change
  .github/workflows/build.yml
  MANIFEST.in
Labels: infrastructure

#304 workflows_mgr: swallow client connect exceptions
  CHANGES.md
  cylc/uiserver/tests/conftest.py
  cylc/uiserver/tests/test_workflows_mgr.py
  cylc/uiserver/workflows_mgr.py
Labels: bug

#306 data_store_mgr: catch possible error
  cylc/uiserver/data_store_mgr.py
Labels: bug, small

#318 Fix test, update type annotation
  cylc/uiserver/config_util.py
  cylc/uiserver/tests/test_config.py
Labels: small
