Repository cylc/cylc-uiserver, pull requests merged in 2023-08, with the labels that each got.

#480 Update README
  README.md
Labels: small

#483 Fix bug with SQL query for analysis view
  cylc/uiserver/schema.py
Labels: bug

#450 setup: migrate to jupyter server 2
  .github/workflows/build.yml
  .github/workflows/test.yml
  CHANGES.md
  cylc/uiserver/app.py
  cylc/uiserver/authorise.py
  cylc/uiserver/handlers.py
  cylc/uiserver/jupyter_config.py
  cylc/uiserver/tests/conftest.py
  cylc/uiserver/tests/test_auth.py
  cylc/uiserver/tests/test_handlers.py
  setup.cfg
Labels: security

#455 Handle trying to play workflows which require upgrade
  CHANGES.md
  cylc/uiserver/resolvers.py
  cylc/uiserver/schema.py
Labels: small
