Repository cylc/cylc-uiserver, pull requests merged in 2023-01, with the labels that each got.

#402 Manual PR: Update copyright on 1.1.x
  README.md
Labels: small

#405 Update changelog
  CHANGES.md
Labels: small

#370 Add gui workflow arg
  CHANGES.md
  cylc/uiserver/app.py
  cylc/uiserver/jupyter_config.py
  cylc/uiserver/scripts/gui.py
  cylc/uiserver/tests/test_gui.py
  setup.cfg
Labels: small

#413 Update CHANGES.md
  CHANGES.md
Labels: small

#414 gui: fix browser open on macos
  cylc/uiserver/scripts/gui.py
Labels: bug

#415 Fix URL for `cylc gui <workflow-id>`
  CHANGES.md
  cylc/uiserver/app.py
  cylc/uiserver/scripts/gui.py
  cylc/uiserver/tests/test_gui.py
Labels: bug, small
