Repository cylc/cylc-uiserver, pull requests merged in 2023-07, with the labels that each got.

#463 Fix possible silent failure to connect to workflow
  CHANGES.md
  cylc/uiserver/workflows_mgr.py
Labels: bug

#471 Logs subscription: tidy error message for when a log file is deleted
  cylc/uiserver/resolvers.py
  cylc/uiserver/tests/test_resolvers.py
Labels: small

#478 GH Actions: enhancements to `update_ui` workflow
  .github/workflows/update_ui.yml
Labels: small, infrastructure

#479 pin to next dev release
  .github/workflows/build.yml
  cylc/uiserver/__init__.py
  setup.cfg
Labels: small
