Repository cylc/cylc-uiserver, pull requests merged in 2024-07, with the labels that each got.

#613 Auth tidy
  cylc/uiserver/app.py
  cylc/uiserver/authorise.py
  cylc/uiserver/tests/test_authorise.py
Labels: authorization

#607 Log any cat-log failure when listing log files
  cylc/uiserver/resolvers.py
Labels: small

#612 More gracefully override JPS `ExtensionApp.config_file_paths`
  cylc/uiserver/app.py
  cylc/uiserver/tests/conftest.py
  cylc/uiserver/tests/test_auth.py
Labels: small

#608 GH Actions: update MacOS version
  .github/workflows/test.yml
Labels: small, infrastructure
