Repository cylc/cylc-uiserver, pull requests merged in 2024-04, with the labels that each got.

#582 GH Actions: add branch sync workflow from master
  .github/workflows/branch_sync.yml
Labels: small, infrastructure

#588 Upper pin pytest
  setup.cfg
Labels: small, dependencies

#590 Hub: remove outdated workaround
  cylc/uiserver/handlers.py
  cylc/uiserver/scripts/hub.py
Labels: small
